name: aupnix_new
description: "AUPNIX"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.2
  app_links: ^7.2.1
  geolocator: ^14.0.3
  geocoding: ^5.0.0
  image_picker: ^1.2.3
  image: ^4.10.1
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  assets:
    - assets/images/
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/aupnix_app_icon.png"
