import '../models/customer_product.dart';

class CustomerProductCatalog {
  CustomerProductCatalog._();

  static final List<CustomerProduct> products = <CustomerProduct>[
    // Milk & Dairy
    const CustomerProduct(
      id: 'fresh-milk-1l',
      name: 'Fresh Milk',
      unit: '1 L',
      image: 'assets/images/Milk & Dairy.png',
      category: 'Milk & Dairy',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 68,
    ),
    const CustomerProduct(
      id: 'toned-milk-1l',
      name: 'Toned Milk',
      unit: '1 L',
      image: 'assets/images/Milk & Dairy.png',
      category: 'Milk & Dairy',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 58,
    ),
    const CustomerProduct(
      id: 'full-cream-milk-1l',
      name: 'Full Cream Milk',
      unit: '1 L',
      image: 'assets/images/Milk & Dairy.png',
      category: 'Milk & Dairy',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 72,
    ),
    const CustomerProduct(
      id: 'curd-500g',
      name: 'Curd',
      unit: '500 g',
      image: 'assets/images/Milk & Dairy.png',
      category: 'Milk & Dairy',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 45,
    ),
    const CustomerProduct(
      id: 'greek-yogurt-400g',
      name: 'Greek Yogurt',
      unit: '400 g',
      image: 'assets/images/Milk & Dairy.png',
      category: 'Milk & Dairy',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 95,
    ),
    const CustomerProduct(
      id: 'paneer-200g',
      name: 'Paneer',
      unit: '200 g',
      image: 'assets/images/Milk & Dairy.png',
      category: 'Milk & Dairy',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 85,
    ),
    const CustomerProduct(
      id: 'butter-100g',
      name: 'Butter',
      unit: '100 g',
      image: 'assets/images/Milk & Dairy.png',
      category: 'Milk & Dairy',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 58,
    ),
    const CustomerProduct(
      id: 'cheese-200g',
      name: 'Cheese',
      unit: '200 g',
      image: 'assets/images/Milk & Dairy.png',
      category: 'Milk & Dairy',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 125,
    ),

    // Snacks
    const CustomerProduct(
      id: 'potato-chips-100g',
      name: 'Potato Chips',
      unit: '100 g',
      image: 'assets/images/Snacks.png',
      category: 'Snacks',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 40,
    ),
    const CustomerProduct(
      id: 'namkeen-200g',
      name: 'Namkeen',
      unit: '200 g',
      image: 'assets/images/Snacks.png',
      category: 'Snacks',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 55,
    ),
    const CustomerProduct(
      id: 'biscuits-200g',
      name: 'Biscuits',
      unit: '200 g',
      image: 'assets/images/Snacks.png',
      category: 'Snacks',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 35,
    ),
    const CustomerProduct(
      id: 'cookies-150g',
      name: 'Cookies',
      unit: '150 g',
      image: 'assets/images/Snacks.png',
      category: 'Snacks',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 60,
    ),
    const CustomerProduct(
      id: 'popcorn-100g',
      name: 'Popcorn',
      unit: '100 g',
      image: 'assets/images/Snacks.png',
      category: 'Snacks',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 45,
    ),
    const CustomerProduct(
      id: 'roasted-peanuts-200g',
      name: 'Roasted Peanuts',
      unit: '200 g',
      image: 'assets/images/Snacks.png',
      category: 'Snacks',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 50,
    ),
    const CustomerProduct(
      id: 'trail-mix-200g',
      name: 'Trail Mix',
      unit: '200 g',
      image: 'assets/images/Snacks.png',
      category: 'Snacks',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 120,
    ),
    const CustomerProduct(
      id: 'nachos-150g',
      name: 'Nachos',
      unit: '150 g',
      image: 'assets/images/Snacks.png',
      category: 'Snacks',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 75,
    ),

    // Beverages
    const CustomerProduct(
      id: 'mineral-water-1l',
      name: 'Mineral Water',
      unit: '1 L',
      image: 'assets/images/Beverages.png',
      category: 'Beverages',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 20,
    ),
    const CustomerProduct(
      id: 'soft-drink-750ml',
      name: 'Soft Drink',
      unit: '750 ml',
      image: 'assets/images/Beverages.png',
      category: 'Beverages',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 40,
    ),
    const CustomerProduct(
      id: 'fruit-juice-1l',
      name: 'Fruit Juice',
      unit: '1 L',
      image: 'assets/images/Beverages.png',
      category: 'Beverages',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 110,
    ),
    const CustomerProduct(
      id: 'cold-coffee-250ml',
      name: 'Cold Coffee',
      unit: '250 ml',
      image: 'assets/images/Beverages.png',
      category: 'Beverages',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 55,
    ),
    const CustomerProduct(
      id: 'green-tea-25-bags',
      name: 'Green Tea',
      unit: '25 Bags',
      image: 'assets/images/Beverages.png',
      category: 'Beverages',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 95,
    ),
    const CustomerProduct(
      id: 'energy-drink-250ml',
      name: 'Energy Drink',
      unit: '250 ml',
      image: 'assets/images/Beverages.png',
      category: 'Beverages',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 125,
    ),
    const CustomerProduct(
      id: 'lassi-200ml',
      name: 'Lassi',
      unit: '200 ml',
      image: 'assets/images/Beverages.png',
      category: 'Beverages',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 30,
    ),
    const CustomerProduct(
      id: 'coconut-water-1l',
      name: 'Coconut Water',
      unit: '1 L',
      image: 'assets/images/Beverages.png',
      category: 'Beverages',
      pricingType: CustomerProductPricingType.fluctuatingAverage,
      averageNearbyPrice: 85,
    ),

    // Staples
    const CustomerProduct(
      id: 'rice-5kg',
      name: 'Rice',
      unit: '5 kg',
      image: 'assets/images/Staples.png',
      category: 'Staples',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 320,
    ),
    const CustomerProduct(
      id: 'wheat-flour-5kg',
      name: 'Wheat Flour',
      unit: '5 kg',
      image: 'assets/images/Staples.png',
      category: 'Staples',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 260,
    ),
    const CustomerProduct(
      id: 'toor-dal-1kg',
      name: 'Toor Dal',
      unit: '1 kg',
      image: 'assets/images/Staples.png',
      category: 'Staples',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 145,
    ),
    const CustomerProduct(
      id: 'sugar-1kg',
      name: 'Sugar',
      unit: '1 kg',
      image: 'assets/images/Staples.png',
      category: 'Staples',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 48,
    ),
    const CustomerProduct(
      id: 'salt-1kg',
      name: 'Salt',
      unit: '1 kg',
      image: 'assets/images/Staples.png',
      category: 'Staples',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 25,
    ),
    const CustomerProduct(
      id: 'cooking-oil-1l',
      name: 'Cooking Oil',
      unit: '1 L',
      image: 'assets/images/Staples.png',
      category: 'Staples',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 135,
    ),
    const CustomerProduct(
      id: 'chana-dal-1kg',
      name: 'Chana Dal',
      unit: '1 kg',
      image: 'assets/images/Staples.png',
      category: 'Staples',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 95,
    ),
    const CustomerProduct(
      id: 'poha-1kg',
      name: 'Poha',
      unit: '1 kg',
      image: 'assets/images/Staples.png',
      category: 'Staples',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 70,
    ),

    // Fruits & Vegetables
    const CustomerProduct(
      id: 'fresh-bananas-1kg',
      name: 'Fresh Bananas',
      unit: '1 kg',
      image: 'assets/images/Fruits & Vegetables.png',
      category: 'Fruits & Vegetables',
      pricingType: CustomerProductPricingType.fluctuatingAverage,
      averageNearbyPrice: 52,
    ),
    const CustomerProduct(
      id: 'fresh-tomatoes-1kg',
      name: 'Fresh Tomatoes',
      unit: '1 kg',
      image: 'assets/images/Fruits & Vegetables.png',
      category: 'Fruits & Vegetables',
      pricingType: CustomerProductPricingType.fluctuatingAverage,
      averageNearbyPrice: 48,
    ),
    const CustomerProduct(
      id: 'fresh-apples-1kg',
      name: 'Fresh Apples',
      unit: '1 kg',
      image: 'assets/images/Fruits & Vegetables.png',
      category: 'Fruits & Vegetables',
      pricingType: CustomerProductPricingType.fluctuatingAverage,
      averageNearbyPrice: 180,
    ),
    const CustomerProduct(
      id: 'fresh-spinach-1bunch',
      name: 'Fresh Spinach',
      unit: '1 bunch',
      image: 'assets/images/Fruits & Vegetables.png',
      category: 'Fruits & Vegetables',
      pricingType: CustomerProductPricingType.fluctuatingAverage,
      averageNearbyPrice: 30,
    ),
    const CustomerProduct(
      id: 'fresh-potatoes-1kg',
      name: 'Fresh Potatoes',
      unit: '1 kg',
      image: 'assets/images/Fruits & Vegetables.png',
      category: 'Fruits & Vegetables',
      pricingType: CustomerProductPricingType.fluctuatingAverage,
      averageNearbyPrice: 40,
    ),
    const CustomerProduct(
      id: 'fresh-onions-1kg',
      name: 'Fresh Onions',
      unit: '1 kg',
      image: 'assets/images/Fruits & Vegetables.png',
      category: 'Fruits & Vegetables',
      pricingType: CustomerProductPricingType.fluctuatingAverage,
      averageNearbyPrice: 45,
    ),
    const CustomerProduct(
      id: 'fresh-carrots-1kg',
      name: 'Fresh Carrots',
      unit: '1 kg',
      image: 'assets/images/Fruits & Vegetables.png',
      category: 'Fruits & Vegetables',
      pricingType: CustomerProductPricingType.fluctuatingAverage,
      averageNearbyPrice: 55,
    ),
    const CustomerProduct(
      id: 'fresh-cucumbers-1kg',
      name: 'Fresh Cucumbers',
      unit: '1 kg',
      image: 'assets/images/Fruits & Vegetables.png',
      category: 'Fruits & Vegetables',
      pricingType: CustomerProductPricingType.fluctuatingAverage,
      averageNearbyPrice: 50,
    ),

    // Personal Care
    const CustomerProduct(
      id: 'shampoo-340ml',
      name: 'Shampoo',
      unit: '340 ml',
      image: 'assets/images/Personal Care.png',
      category: 'Personal Care',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 199,
    ),
    const CustomerProduct(
      id: 'soap-100g',
      name: 'Soap',
      unit: '100 g',
      image: 'assets/images/Personal Care.png',
      category: 'Personal Care',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 45,
    ),
    const CustomerProduct(
      id: 'toothpaste-150g',
      name: 'Toothpaste',
      unit: '150 g',
      image: 'assets/images/Personal Care.png',
      category: 'Personal Care',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 95,
    ),
    const CustomerProduct(
      id: 'face-wash-100ml',
      name: 'Face Wash',
      unit: '100 ml',
      image: 'assets/images/Personal Care.png',
      category: 'Personal Care',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 175,
    ),
    const CustomerProduct(
      id: 'body-lotion-200ml',
      name: 'Body Lotion',
      unit: '200 ml',
      image: 'assets/images/Personal Care.png',
      category: 'Personal Care',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 210,
    ),
    const CustomerProduct(
      id: 'hair-oil-200ml',
      name: 'Hair Oil',
      unit: '200 ml',
      image: 'assets/images/Personal Care.png',
      category: 'Personal Care',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 140,
    ),
    const CustomerProduct(
      id: 'deodorant-150ml',
      name: 'Deodorant',
      unit: '150 ml',
      image: 'assets/images/Personal Care.png',
      category: 'Personal Care',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 225,
    ),
    const CustomerProduct(
      id: 'hand-wash-250ml',
      name: 'Hand Wash',
      unit: '250 ml',
      image: 'assets/images/Personal Care.png',
      category: 'Personal Care',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 110,
    ),

    // Household
    const CustomerProduct(
      id: 'dishwash-liquid-500ml',
      name: 'Dishwash Liquid',
      unit: '500 ml',
      image: 'assets/images/Household.png',
      category: 'Household',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 120,
    ),
    const CustomerProduct(
      id: 'laundry-detergent-1kg',
      name: 'Laundry Detergent',
      unit: '1 kg',
      image: 'assets/images/Household.png',
      category: 'Household',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 110,
    ),
    const CustomerProduct(
      id: 'floor-cleaner-1l',
      name: 'Floor Cleaner',
      unit: '1 L',
      image: 'assets/images/Household.png',
      category: 'Household',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 145,
    ),
    const CustomerProduct(
      id: 'toilet-cleaner-500ml',
      name: 'Toilet Cleaner',
      unit: '500 ml',
      image: 'assets/images/Household.png',
      category: 'Household',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 95,
    ),
    const CustomerProduct(
      id: 'glass-cleaner-500ml',
      name: 'Glass Cleaner',
      unit: '500 ml',
      image: 'assets/images/Household.png',
      category: 'Household',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 105,
    ),
    const CustomerProduct(
      id: 'garbage-bags-30',
      name: 'Garbage Bags',
      unit: '30 bags',
      image: 'assets/images/Household.png',
      category: 'Household',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 85,
    ),
    const CustomerProduct(
      id: 'scrub-pads-5',
      name: 'Scrub Pads',
      unit: '5 pieces',
      image: 'assets/images/Household.png',
      category: 'Household',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 55,
    ),
    const CustomerProduct(
      id: 'kitchen-towels-4',
      name: 'Kitchen Towels',
      unit: '4 pieces',
      image: 'assets/images/Household.png',
      category: 'Household',
      pricingType: CustomerProductPricingType.fixedMrp,
      mrp: 90,
    ),
    // Featured Home Products
  ];

  static CustomerProduct? findByName(String name) {
    final normalizedName = name.trim().toLowerCase();

    for (final product in products) {
      if (product.name.toLowerCase() == normalizedName) {
        return product;
      }
    }

    return null;
  }

  static CustomerProduct? findByNameAndUnit(
    String name,
    String unit,
  ) {
    final normalizedName = name.trim().toLowerCase();
    final normalizedUnit = unit.trim().toLowerCase();

    for (final product in products) {
      if (product.name.toLowerCase() == normalizedName &&
          product.unit.toLowerCase() == normalizedUnit) {
        return product;
      }
    }

    return null;
  }
}


